### PR TITLE
revised solution for span raw html problem

### PR DESCRIPTION
**Pull request by tiberiusferreira**
This is my attempt at your proposed solution. 
About your comment on the previous attempt
 "Works for initial render, but appears not to update on changes." 
you mean it does not render correctly on router changes for example?

### CODE REVIEW

**Comment by David-OConnor** [comment]
> you mean it does not render correctly on router changes for example?
Correct. I haven't looked into the details or done any troubleshooting, but a test on the homepage shows the guide page text not updating.

**Comment by tiberiusferreira** [comment]
> Great find on fixing the prob with my code.

 Thanks! 
> edit: A glance at this PR shows the same issue; I think we need to update some patching code too.

Yes, I cloned the homepage example repo and can reproduce it. If I find a fix I'll let you know.

**Comment by tiberiusferreira** [comment]
The weird part is that routing works fine when changing between Guide and Changelog, but not between Guide pages.

**Comment by David-OConnor** [comment]
Yeah - likely because we're switching between an HTML el and a non-HTML el, which have diff tags, and therefore force a full rerender.

I'm examining a different approach, where the `from_html` and `from_markdown` funcs create full vdom Els, instead of handling it during render.

**Comment by tiberiusferreira** [comment]
Well, I think I found the problem:
https://github.com/David-OConnor/seed/blob/85aa90d22fda179e00c2bd1eab9b2dbb300b9404/src/websys_bridge.rs#L332-L337 
Here we set the inner_html of the element actual DOM node, which is the ```<span>``` we did not actually attach to the DOM during first rendering. 

I tried to fix it by keeping references of the nodes which we attached during the first render and modifying those, but it got complicated and messy. The real problem is the vdom and actual DOM not in sync anymore.

I think the best solution is what you are examining, creating full vdom Els from `from_html` and `from_markdown`. 

I imagine it would involve parsing the html string passed. If so, long term this could be done at compile time and provide an additional check of correctness and help catch typos and invalid html.

**Comment by David-OConnor** [comment]
Nice find again. Don't need to manually parse; can set inner_html on a dummy el, then create a nested vdom node from it. Almost have it working.

**Comment by tiberiusferreira** [comment]
Thanks for the changes.

 After trying it to render some SVGs, it had some problems. (It would not render anything).
I thought it was because iterating over a hashmap to set the attributes does not preserve ordering and it might affect it. So I tried changing the hashmap to https://github.com/bluss/indexmap .

Now the attributes order is preserved, but it still does not render (while before it rendered fine). 

I don't know yet the source of the problem, but if I find it, I will let you know. 

Here is the code I was testing with: https://github.com/tiberiusferreira/festera_seed

**Comment by David-OConnor** [comment]
Still haven't figured out what's wrong with the latest version. For the homepage, it alternates between several errors when switching pages.

**Comment by David-OConnor** [comment]
The latest commit works for the homepage, although I still don't understand the root cause of the problems: Instead of forcing a panic, it now recovers, and outputs a note in the console. Is this working for you?

Is the SVG problem you mentioned a separate issue?

**Comment by tiberiusferreira** [comment]
Unfortunately it's not working for me :( 
Using Commit 85aa90d22fda179e00c2bd1eab9b2dbb300b9404 I get:
screen shot 2019-02-16 at 23 36 58

and using latest ( bd90f1cb15c9fca98398a63019d9829ce6d1a295 ) I get: 

screen shot 2019-02-16 at 23 36 08

Once I get some time I will try to help pinpoint the issue. The code I'm testing against is this one https://github.com/tiberiusferreira/festera_seed

**Comment by David-OConnor** [comment]
Weird; that was intermediate gibberish text I added to debug that shouldn't be in the commit.

**Comment by David-OConnor** [comment]
Two observations: It appears to be ignoring the `<g>` tag. I'm not sure if the xml metadata is being ignored as well.

**Comment by tiberiusferreira** [comment]
Just tried with 
```
[dependencies]
seed = {git = "https://github.com/David-OConnor/seed.git", rev = "bd90f1cb15c9fca98398a63019d9829ce6d1a295"}
```
and now the MOO text is gone, but the SVG is still missing:

screen shot 2019-02-17 at 00 14 49

Thanks for looking into it.

**Comment by David-OConnor** [comment]
More info: The SVG bug happens with or without Raw HTML, and if you edit the SVG tag in the Firefox console.... any edit at all, and it will render.

**Comment by David-OConnor** [comment]
Fixed in latest commit. The problem was not setting the namespace. There still appears to be a problem with creating SVGs using macros.

**Comment by tiberiusferreira** [comment]
Yep, it works! Thank you very much.

**Pull request closed without merging**
