### PR TITLE
ci: Enable test with wasm-bindgen-test and wasm-pack

### PR DESCRIPTION
**Pull request by naufraghi**
- add firefox as addon
- cache cargo (allow failure on cargo install)
- disable windows because of https://travis-ci.org/naufraghi/seed/jobs/475998812#L630

### CODE REVIEW

**Comment by naufraghi** [comment]
There is a issue about something very similar, the fix should be already merged (https://github.com/rustwasm/wasm-pack/issues/380) but will be released in 0.6.0 (we are using the current latest 0.5.1)

**Comment by naufraghi** [comment]
In the next MR I have added the badge in the readme, but @David-OConnor need to enable travis for this repo (every time I forget this step can be done form https://travis-ci.org/account/repositories and not from github)

**Comment by David-OConnor** [comment]
Added readme badge. I've been having trouble with tests due to web_sys funcs not working in normal tests; looks like #[wasm_bindgen_test] attempts to sort this out.

**Comment by naufraghi** [comment]
Oh, yes, I forgot to link the docs.
Beside that, this diff fixes the error on [travis](https://travis-ci.org/David-OConnor/seed/jobs/476389947#L1148):

```diff
diff --git a/src/dom_types.rs b/src/dom_types.rs
index 63fa2a3..51b0869 100644
--- a/src/dom_types.rs
+++ b/src/dom_types.rs
@@ -970,10 +970,10 @@ pub mod tests {
     // todo 'cannot call wasm-bindgen imported functions on non-wasm targets' error
     #[wasm_bindgen_test]
     pub fn single() {
-        let expected = "<div>\ntest\n</div>";
+        let expected = "<div>test</div>";
 
         let mut el: El<Msg> = div![ "test" ];
         crate::vdom::setup_els(&crate::util::document(), &mut el, 0, 0);
-        assert_eq!(expected, el.el_ws.unwrap().inner_html());
+        assert_eq!(expected, el.el_ws.unwrap().outer_html());
     }
 }
```

**Comment by naufraghi** [comment]
Oh, yes, I forgot to link the docs.
Beside that, this diff fixes the error on [travis](https://travis-ci.org/David-OConnor/seed/jobs/476389947#L1148):

```diff
diff --git a/src/dom_types.rs b/src/dom_types.rs
index 63fa2a3..51b0869 100644
--- a/src/dom_types.rs
+++ b/src/dom_types.rs
@@ -970,10 +970,10 @@ pub mod tests {
     // todo 'cannot call wasm-bindgen imported functions on non-wasm targets' error
     #[wasm_bindgen_test]
     pub fn single() {
-        let expected = "<div>\ntest\n</div>";
+        let expected = "<div>test</div>";
 
         let mut el: El<Msg> = div![ "test" ];
         crate::vdom::setup_els(&crate::util::document(), &mut el, 0, 0);
-        assert_eq!(expected, el.el_ws.unwrap().inner_html());
+        assert_eq!(expected, el.el_ws.unwrap().outer_html());
     }
 }
```

**Pull request merged**
