### PR TITLE
theoretical minimum: install wasm-pack

### PR DESCRIPTION
**Pull request by ysz**
Had to install wask-pack

### CODE REVIEW

**Comment by MartinKavik** [comment]
It sounds like a bug, `cargo-make` should install it automatically.

**Comment by ysz** [comment]
> `cargo-make` should install it automatically

I thought so too but it didn't.

**Comment by MartinKavik** [comment]
Could you try it with changes in https://github.com/David-OConnor/seed-quickstart/issues/10. please?

**Comment by David-OConnor** [comment]
Closing, since this is an issue with the quickstart repo.

**Pull request closed without merging**
